spring:
  datasource :
    url: jdbc:mysql://localhost:3679/temppp?createDatabaseIfNotExist=true
    username: root
    password: kshithi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
     ddl-auto: update
   properties:
      dialect: org.hibernate.dialect.MySQLDialect
   show-sql: true